---

- name: get redis
  get_url: url=http://download.redis.io/releases/redis-{{ REDIS_VERSION }}.tar.gz dest=/usr/local/src/redis-{{ REDIS_VERSION }}.tar.gz force=no

- name: install redis
  script: script/install.sh {{ REDIS_VERSION }} creates=/usr/local/bin/redis-cli 

- name: copy redis service
  template: src=redis-server.j2 dest=/etc/init.d/redis-{{ REDIS_PORT }} mode=755

- name: copy redis.conf
  template: src=redis.conf.j2 dest=/etc/redis/redis_{{ REDIS_PORT }}.conf
  notify:
    - restart redis
